### ISSUE TITLE
upup doesnt play nice with other service workers

### ISSUE THREAD

**Issue by japrescott** [TalAter/UpUp#112]
in my observation, upup doesn't play nice with other service workers. I am primarily talking about [google analytics sw](https://github.com/GoogleChrome/sw-helpers/tree/master/packages/sw-offline-google-analytics#googofflinegoogleanalyticsinitialize) which is registered before upup, but only upup seems to register. When removing upup, analytics sw is registered. 

## Expected Behavior
registering multiple service workers should show them listed in chrome dev tools under 'Application'

## Current Behavior
Only upup is listed as registered service worker

## Your Environment
* Version used: upup0.3 
* Browser Name and version: Chromium 56.0.2924.76 
* Operating System and version (desktop or mobile): Linux

**Comment by TalAter** [comment]
Only a single service worker may be active on the page at one time.

To allow UpUp to work together with other service workers, it will need to be modified so that it is loaded completely different, and imported into another service worker.

The philosophy behind UpUp is to solve a simple use case, without forcing the user to undergo a complex integration as would be required for the approach described above.
