### ISSUE TITLE
demo-site marked as dangerous in chrome

### ISSUE THREAD

**Issue by tjoen** [TalAter/UpUp#46]
Gives a warning when opening  https://www.talater.com/upup/
Unsure about if this is because of missing certificates, hacking or malicious code on the page.

You should fix it asap though

**Comment by TalAter** [comment]
Thanks for posting this.

I'm trying to fix this.

My guess is this is due to some old .exe file that has been on the site for the past 4 years. It contains a browser extension which I created using a third party's service. I've removed it from the site, and there are now no executable files at all on the domain.

**Comment by ghprod** [comment]
I have same issue 

![image](https://cloud.githubusercontent.com/assets/1922652/9666584/4072a8e2-52a1-11e5-9bd8-b8e94b29a022.png)

**Comment by TalAter** [comment]
I just received a message from Google that they rechecked it and detected no malware. The site is working again. :tada:
Does it work for you?

**Comment by ghprod** [comment]
Yes its works now :dancer:
